// Start of user code Copyright
/*
 * Copyright (c) 2020 Contributors to the Eclipse Foundation
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Distribution License 1.0 which is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Simple
 *
 * This file is generated by Lyo Designer (https://www.eclipse.org/lyo/)
 */
// End of user code

package cetic.be.objectiver.oslc.services;

import java.io.IOException;
import java.io.PrintWriter;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.TreeSet;

import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.ws.rs.Consumes;
import javax.ws.rs.DELETE;
import javax.ws.rs.FormParam;
import javax.ws.rs.GET;
import javax.ws.rs.HeaderParam;
import javax.ws.rs.POST;
import javax.ws.rs.PUT;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.QueryParam;
import javax.ws.rs.WebApplicationException;
import javax.ws.rs.core.Context;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.MultivaluedMap;
import javax.ws.rs.core.Response;
import javax.ws.rs.core.Response.Status;
import javax.ws.rs.core.UriInfo;
import javax.ws.rs.core.UriBuilder;

import org.apache.wink.json4j.JSONException;
import org.apache.wink.json4j.JSONObject;
import org.eclipse.lyo.oslc4j.provider.json4j.JsonHelper;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.eclipse.lyo.oslc4j.core.OSLC4JUtils;
import org.eclipse.lyo.oslc4j.core.annotation.OslcCreationFactory;
import org.eclipse.lyo.oslc4j.core.annotation.OslcDialog;
import org.eclipse.lyo.oslc4j.core.annotation.OslcDialogs;
import org.eclipse.lyo.oslc4j.core.annotation.OslcQueryCapability;
import org.eclipse.lyo.oslc4j.core.annotation.OslcService;
import org.eclipse.lyo.oslc4j.core.model.Compact;
import org.eclipse.lyo.oslc4j.core.model.OslcConstants;
import org.eclipse.lyo.oslc4j.core.model.OslcMediaType;
import org.eclipse.lyo.oslc4j.core.model.Preview;
import org.eclipse.lyo.oslc4j.core.model.ServiceProvider;
import org.eclipse.lyo.oslc4j.core.model.Link;
import org.eclipse.lyo.oslc4j.core.model.AbstractResource;

import cetic.be.objectiver.oslc.ObjectiverManager;
import cetic.be.objectiver.oslc.ObjectiverConstants;
import cetic.be.objectiver.oslc.resources.Oslc_objectiverDomainConstants;
import cetic.be.objectiver.oslc.servlet.ServiceProviderCatalogSingleton;
import cetic.be.objectiver.oslc.resources.Goal;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.responses.ApiResponse;

import org.eclipse.lyo.server.ui.model.PreviewFactory;
// Start of user code imports
// End of user code

// Start of user code pre_class_code
// End of user code
@Path("Goals")
public class GoalService
{
    @Context private HttpServletRequest httpServletRequest;
    @Context private HttpServletResponse httpServletResponse;
    @Context private UriInfo uriInfo;

    private static final Logger log = LoggerFactory.getLogger(GoalService.class);

    // Start of user code class_attributes
    // End of user code

    // Start of user code class_methods
    // End of user code

    public GoalService()
    {
        super();
    }

    private void addCORSHeaders (final HttpServletResponse httpServletResponse) {
        //UI preview can be blocked by CORS policy.
        //add select CORS headers to every response that is embedded in an iframe.
        httpServletResponse.addHeader("Access-Control-Allow-Origin", "*");
        httpServletResponse.addHeader("Access-Control-Allow-Methods", "GET, OPTIONS, HEAD");
        httpServletResponse.addHeader("Access-Control-Allow-Headers", "origin, content-type, accept, authorization");
        httpServletResponse.addHeader("Access-Control-Allow-Credentials", "true");
    }

    @GET
    @Path("{goalId}")
    @Produces({OslcMediaType.APPLICATION_RDF_XML, OslcMediaType.APPLICATION_JSON_LD, OslcMediaType.TEXT_TURTLE, OslcMediaType.APPLICATION_XML, OslcMediaType.APPLICATION_JSON})
    @Operation(
        summary = "GET for resources of type {'" + Oslc_objectiverDomainConstants.GOAL_LOCALNAME + "'}",
        description = "GET for resources of type {'" + "<a href=\"" + Oslc_objectiverDomainConstants.GOAL_TYPE + "\">" + Oslc_objectiverDomainConstants.GOAL_LOCALNAME + "</a>" + "'}" +
            ", with respective resource shapes {'" + "<a href=\"" + "../services/" + OslcConstants.PATH_RESOURCE_SHAPES + "/" + Oslc_objectiverDomainConstants.GOAL_PATH + "\">" + Oslc_objectiverDomainConstants.GOAL_LOCALNAME + "</a>" + "'}",
        responses = {
            @ApiResponse(description = "default response", content = {@Content(mediaType = OslcMediaType.APPLICATION_RDF_XML), @Content(mediaType = OslcMediaType.APPLICATION_XML), @Content(mediaType = OslcMediaType.APPLICATION_JSON), @Content(mediaType = OslcMediaType.TEXT_TURTLE), @Content(mediaType = MediaType.TEXT_HTML), @Content(mediaType = OslcMediaType.APPLICATION_X_OSLC_COMPACT_XML)})
        }
    )
    public Goal getGoal(
                @PathParam("goalId") final String goalId
        ) throws IOException, ServletException, URISyntaxException
    {
        // Start of user code getResource_init
        // End of user code

        final Goal aGoal = ObjectiverManager.getGoal(httpServletRequest, goalId);

        if (aGoal != null) {
            // Start of user code getGoal
            // End of user code
            httpServletResponse.setHeader("ETag", ObjectiverManager.getETagFromGoal(aGoal));
            httpServletResponse.addHeader(ObjectiverConstants.HDR_OSLC_VERSION, ObjectiverConstants.OSLC_VERSION_V2);
            return aGoal;
        }

        throw new WebApplicationException(Status.NOT_FOUND);
    }

    @GET
    @Path("{goalId}")
    @Produces({ MediaType.TEXT_HTML })
    @Operation(
        summary = "GET for resources of type {'" + Oslc_objectiverDomainConstants.GOAL_LOCALNAME + "'}",
        description = "GET for resources of type {'" + "<a href=\"" + Oslc_objectiverDomainConstants.GOAL_TYPE + "\">" + Oslc_objectiverDomainConstants.GOAL_LOCALNAME + "</a>" + "'}" +
            ", with respective resource shapes {'" + "<a href=\"" + "../services/" + OslcConstants.PATH_RESOURCE_SHAPES + "/" + Oslc_objectiverDomainConstants.GOAL_PATH + "\">" + Oslc_objectiverDomainConstants.GOAL_LOCALNAME + "</a>" + "'}",
        responses = {
            @ApiResponse(description = "default response", content = {@Content(mediaType = OslcMediaType.APPLICATION_RDF_XML), @Content(mediaType = OslcMediaType.APPLICATION_XML), @Content(mediaType = OslcMediaType.APPLICATION_JSON), @Content(mediaType = OslcMediaType.TEXT_TURTLE), @Content(mediaType = MediaType.TEXT_HTML), @Content(mediaType = OslcMediaType.APPLICATION_X_OSLC_COMPACT_XML)})
        }
    )
    public void getGoalAsHtml(
        @PathParam("goalId") final String goalId
        ) throws ServletException, IOException, URISyntaxException
    {
        // Start of user code getGoalAsHtml_init
        // End of user code

        final Goal aGoal = ObjectiverManager.getGoal(httpServletRequest, goalId);

        if (aGoal != null) {
            httpServletRequest.setAttribute("aGoal", aGoal);
            // Start of user code getGoalAsHtml_setAttributes
            // End of user code

            httpServletRequest.setAttribute("aResource", aGoal);
            httpServletRequest.setAttribute("resourceTypeName", Oslc_objectiverDomainConstants.GOAL_LOCALNAME);
            httpServletRequest.setAttribute("shapeUri", UriBuilder.fromUri(OSLC4JUtils.getServletURI()).path(OslcConstants.PATH_RESOURCE_SHAPES).path(Oslc_objectiverDomainConstants.GOAL_PATH).build());
            RequestDispatcher rd = httpServletRequest.getRequestDispatcher("/cetic/be/objectiver/oslc/viewresource.jsp");
            rd.forward(httpServletRequest,httpServletResponse);
            return;
        }

        throw new WebApplicationException(Status.NOT_FOUND);
    }

    @GET
    @Path("{goalId}")
    @Produces({OslcMediaType.APPLICATION_X_OSLC_COMPACT_XML})
    @Operation(
        summary = "GET for resources of type {'" + Oslc_objectiverDomainConstants.GOAL_LOCALNAME + "'}",
        description = "GET for resources of type {'" + "<a href=\"" + Oslc_objectiverDomainConstants.GOAL_TYPE + "\">" + Oslc_objectiverDomainConstants.GOAL_LOCALNAME + "</a>" + "'}" +
            ", with respective resource shapes {'" + "<a href=\"" + "../services/" + OslcConstants.PATH_RESOURCE_SHAPES + "/" + Oslc_objectiverDomainConstants.GOAL_PATH + "\">" + Oslc_objectiverDomainConstants.GOAL_LOCALNAME + "</a>" + "'}",
        responses = {
            @ApiResponse(description = "default response", content = {@Content(mediaType = OslcMediaType.APPLICATION_RDF_XML), @Content(mediaType = OslcMediaType.APPLICATION_XML), @Content(mediaType = OslcMediaType.APPLICATION_JSON), @Content(mediaType = OslcMediaType.TEXT_TURTLE), @Content(mediaType = MediaType.TEXT_HTML), @Content(mediaType = OslcMediaType.APPLICATION_X_OSLC_COMPACT_XML)})
        }
    )
    public Compact getGoalCompact(
        @PathParam("goalId") final String goalId
        ) throws ServletException, IOException, URISyntaxException
    {
        String iconUri = OSLC4JUtils.getPublicURI() + "/images/ui_preview_icon.gif";
        String smallPreviewHintHeight = "200px";
        String smallPreviewHintWidth = "300px";
        String largePreviewHintHeight = "400px";
        String largePreviewHintWidth = "600px";

        // Start of user code getGoalCompact_init
        //TODO: adjust the preview height & width values from the default values provided above.
        // End of user code

        final Goal aGoal = ObjectiverManager.getGoal(httpServletRequest, goalId);

        if (aGoal != null) {
            final Compact compact = new Compact();

            compact.setAbout(aGoal.getAbout());
            compact.setTitle(aGoal.toString());

            compact.setIcon(new URI(iconUri));

            //Create and set attributes for OSLC preview resource
            final Preview smallPreview = new Preview();
            smallPreview.setHintHeight(smallPreviewHintHeight);
            smallPreview.setHintWidth(smallPreviewHintWidth);
            smallPreview.setDocument(UriBuilder.fromUri(aGoal.getAbout()).path("smallPreview").build());
            compact.setSmallPreview(smallPreview);

            final Preview largePreview = new Preview();
            largePreview.setHintHeight(largePreviewHintHeight);
            largePreview.setHintWidth(largePreviewHintWidth);
            largePreview.setDocument(UriBuilder.fromUri(aGoal.getAbout()).path("largePreview").build());
            compact.setLargePreview(largePreview);

            httpServletResponse.addHeader(ObjectiverConstants.HDR_OSLC_VERSION, ObjectiverConstants.OSLC_VERSION_V2);
            addCORSHeaders(httpServletResponse);
            return compact;
        }
        throw new WebApplicationException(Status.NOT_FOUND);
    }

    @GET
    @Path("{goalId}/smallPreview")
    @Produces({ MediaType.TEXT_HTML })
    public void getGoalAsHtmlSmallPreview(
        @PathParam("goalId") final String goalId
        ) throws ServletException, IOException, URISyntaxException
    {
        // Start of user code getGoalAsHtmlSmallPreview_init
        // End of user code

        final Goal aGoal = ObjectiverManager.getGoal(httpServletRequest, goalId);

        if (aGoal != null) {
            httpServletRequest.setAttribute("aGoal", aGoal);
            // Start of user code getGoalAsHtmlSmallPreview_setAttributes
            // End of user code

            try {
                httpServletRequest.setAttribute("resourceTitle", aGoal.toString());
                ArrayList<String> getterMethodNames = new ArrayList<String>(Arrays.asList("getName", "getType", "getDef", "getPriority", "getCategory", "getIssue", "getExternalId", "getOpenId", "getDiagrams", "getRefdiagrams"));
                // Start of user code getGoalAsHtmlSmallPreview_setResourceGetterMethods
                //TODO: modify the set of attributes to show in the preview
                // End of user code
                String oslcPreviewDataSetAsString = PreviewFactory.getPreviewAsJsonString(aGoal, getterMethodNames, false);
                httpServletRequest.setAttribute("resourcePreviewDataSet", oslcPreviewDataSetAsString);
            } catch (Exception e) {
                log.error("Could not handle smallPreview", e);
                throw new WebApplicationException("Could not handle smallPreview", e);
            }
            RequestDispatcher rd = httpServletRequest.getRequestDispatcher("/cetic/be/objectiver/oslc/uipreview.jsp");
            httpServletResponse.addHeader(ObjectiverConstants.HDR_OSLC_VERSION, ObjectiverConstants.OSLC_VERSION_V2);
            addCORSHeaders(httpServletResponse);
            rd.forward(httpServletRequest, httpServletResponse);
            return;
        }

        throw new WebApplicationException(Status.NOT_FOUND);
    }

    @GET
    @Path("{goalId}/largePreview")
    @Produces({ MediaType.TEXT_HTML })
    public void getGoalAsHtmlLargePreview(
        @PathParam("goalId") final String goalId
        ) throws ServletException, IOException, URISyntaxException
    {
        // Start of user code getGoalAsHtmlLargePreview_init
        // End of user code

        final Goal aGoal = ObjectiverManager.getGoal(httpServletRequest, goalId);

        if (aGoal != null) {
            httpServletRequest.setAttribute("aGoal", aGoal);
            // Start of user code getGoalAsHtmlLargePreview_setAttributes
            // End of user code

            try {
                httpServletRequest.setAttribute("resourceTitle", aGoal.toString());
                ArrayList<String> getterMethodNames = new ArrayList<String>(Arrays.asList("getName", "getType", "getDef", "getPriority", "getCategory", "getIssue", "getExternalId", "getOpenId", "getDiagrams", "getRefdiagrams"));
                // Start of user code getGoalAsHtmlLargePreview_setResourceGetterMethods
                //TODO: modify the set of attributes to show in the preview
                // End of user code
                String oslcPreviewDataSetAsString = PreviewFactory.getPreviewAsJsonString(aGoal, getterMethodNames, true);
                httpServletRequest.setAttribute("resourcePreviewDataSet", oslcPreviewDataSetAsString);
            } catch (Exception e) {
                log.error("Could not handle largePreview", e);
                throw new WebApplicationException("Could not handle largePreview", e);
            }
            RequestDispatcher rd = httpServletRequest.getRequestDispatcher("/cetic/be/objectiver/oslc/uipreview.jsp");
            httpServletResponse.addHeader(ObjectiverConstants.HDR_OSLC_VERSION, ObjectiverConstants.OSLC_VERSION_V2);
            addCORSHeaders(httpServletResponse);
            rd.forward(httpServletRequest, httpServletResponse);
            return;
        }

        throw new WebApplicationException(Status.NOT_FOUND);
    }
    @DELETE
    @Path("{goalId}")
    @Operation(
        summary = "DELETE for resources of type {'" + Oslc_objectiverDomainConstants.GOAL_LOCALNAME + "'}",
        description = "DELETE for resources of type {'" + "<a href=\"" + Oslc_objectiverDomainConstants.GOAL_TYPE + "\">" + Oslc_objectiverDomainConstants.GOAL_LOCALNAME + "</a>" + "'}" +
            ", with respective resource shapes {'" + "<a href=\"" + "../services/" + OslcConstants.PATH_RESOURCE_SHAPES + "/" + Oslc_objectiverDomainConstants.GOAL_PATH + "\">" + Oslc_objectiverDomainConstants.GOAL_LOCALNAME + "</a>" + "'}",
        responses = {
            @ApiResponse(description = "default response", content = {@Content(mediaType = OslcMediaType.APPLICATION_RDF_XML), @Content(mediaType = OslcMediaType.APPLICATION_XML), @Content(mediaType = OslcMediaType.APPLICATION_JSON), @Content(mediaType = OslcMediaType.TEXT_TURTLE), @Content(mediaType = MediaType.TEXT_HTML), @Content(mediaType = OslcMediaType.APPLICATION_X_OSLC_COMPACT_XML)})
        }
    )
    public Response deleteGoal(
                @PathParam("goalId") final String goalId
        ) throws IOException, ServletException, URISyntaxException
    {
        // Start of user code deleteGoal_init
        // End of user code
        final Goal aResource = ObjectiverManager.getGoal(httpServletRequest, goalId);

        if (aResource != null) {
            // Start of user code deleteGoal
            // End of user code
            boolean deleted = ObjectiverManager.deleteGoal(httpServletRequest, goalId);
            if (deleted)
                return Response.ok().header(ObjectiverConstants.HDR_OSLC_VERSION, ObjectiverConstants.OSLC_VERSION_V2).build();
            else
                throw new WebApplicationException(Status.INTERNAL_SERVER_ERROR);
        }
        throw new WebApplicationException(Status.NOT_FOUND);
    }

    @PUT
    @Path("{goalId}")
    @Consumes({OslcMediaType.APPLICATION_RDF_XML, OslcMediaType.APPLICATION_JSON_LD, OslcMediaType.TEXT_TURTLE, OslcMediaType.APPLICATION_XML, OslcMediaType.APPLICATION_JSON })
    @Operation(
        summary = "PUT for resources of type {'" + Oslc_objectiverDomainConstants.GOAL_LOCALNAME + "'}",
        description = "PUT for resources of type {'" + "<a href=\"" + Oslc_objectiverDomainConstants.GOAL_TYPE + "\">" + Oslc_objectiverDomainConstants.GOAL_LOCALNAME + "</a>" + "'}" +
            ", with respective resource shapes {'" + "<a href=\"" + "../services/" + OslcConstants.PATH_RESOURCE_SHAPES + "/" + Oslc_objectiverDomainConstants.GOAL_PATH + "\">" + Oslc_objectiverDomainConstants.GOAL_LOCALNAME + "</a>" + "'}",
        responses = {
            @ApiResponse(description = "default response", content = {@Content(mediaType = OslcMediaType.APPLICATION_RDF_XML), @Content(mediaType = OslcMediaType.APPLICATION_XML), @Content(mediaType = OslcMediaType.APPLICATION_JSON), @Content(mediaType = OslcMediaType.TEXT_TURTLE), @Content(mediaType = MediaType.TEXT_HTML), @Content(mediaType = OslcMediaType.APPLICATION_X_OSLC_COMPACT_XML)})
        }
    )
    public Response updateGoal(
            @HeaderParam("If-Match") final String eTagHeader,
            @PathParam("goalId") final String goalId ,
            final Goal aResource
        ) throws IOException, ServletException
    {
        // Start of user code updateGoal_init
        // End of user code
        final Goal originalResource = ObjectiverManager.getGoal(httpServletRequest, goalId);

        if (originalResource != null) {
            final String originalETag = ObjectiverManager.getETagFromGoal(originalResource);

            if ((eTagHeader == null) || (originalETag.equals(eTagHeader))) {
                // Start of user code updateGoal
                // End of user code
                final Goal updatedResource = ObjectiverManager.updateGoal(httpServletRequest, aResource, goalId);
                httpServletResponse.setHeader("ETag", ObjectiverManager.getETagFromGoal(updatedResource));
                return Response.ok().header(ObjectiverConstants.HDR_OSLC_VERSION, ObjectiverConstants.OSLC_VERSION_V2).build();
            }
            else {
                throw new WebApplicationException(Status.PRECONDITION_FAILED);
            }
        }
        else {
            throw new WebApplicationException(Status.NOT_FOUND);
        }
    }

}
