// Start of user code Copyright
/*
 * Copyright (c) 2020 Contributors to the Eclipse Foundation
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Distribution License 1.0 which is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Simple
 *
 * This file is generated by Lyo Designer (https://www.eclipse.org/lyo/)
 */
// End of user code

package cetic.be.objectiver.oslc.resources;

import java.net.URI;
import java.net.URISyntaxException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.text.SimpleDateFormat;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.TreeSet;
import java.util.Iterator;

import org.eclipse.lyo.oslc4j.core.annotation.OslcAllowedValue;
import org.eclipse.lyo.oslc4j.core.annotation.OslcDescription;
import org.eclipse.lyo.oslc4j.core.annotation.OslcMemberProperty;
import org.eclipse.lyo.oslc4j.core.annotation.OslcName;
import org.eclipse.lyo.oslc4j.core.annotation.OslcNamespace;
import org.eclipse.lyo.oslc4j.core.annotation.OslcOccurs;
import org.eclipse.lyo.oslc4j.core.annotation.OslcPropertyDefinition;
import org.eclipse.lyo.oslc4j.core.annotation.OslcRdfCollectionType;
import org.eclipse.lyo.oslc4j.core.annotation.OslcRange;
import org.eclipse.lyo.oslc4j.core.annotation.OslcReadOnly;
import org.eclipse.lyo.oslc4j.core.annotation.OslcRepresentation;
import org.eclipse.lyo.oslc4j.core.annotation.OslcResourceShape;
import org.eclipse.lyo.oslc4j.core.annotation.OslcTitle;
import org.eclipse.lyo.oslc4j.core.annotation.OslcValueType;
import org.eclipse.lyo.oslc4j.core.model.AbstractResource;
import org.eclipse.lyo.oslc4j.core.model.Link;
import org.eclipse.lyo.oslc4j.core.model.Occurs;
import org.eclipse.lyo.oslc4j.core.model.OslcConstants;
import org.eclipse.lyo.oslc4j.core.model.Representation;
import org.eclipse.lyo.oslc4j.core.model.ValueType;

import cetic.be.objectiver.oslc.resources.Oslc_objectiverDomainConstants;
import cetic.be.objectiver.oslc.resources.Oslc_objectiverDomainConstants;


// Start of user code imports
// End of user code

@OslcNamespace(Oslc_objectiverDomainConstants.GOAL_NAMESPACE)
@OslcName(Oslc_objectiverDomainConstants.GOAL_LOCALNAME)
@OslcResourceShape(title = "Goal Shape", describes = Oslc_objectiverDomainConstants.GOAL_TYPE)
public interface IGoal
{

    public void addDiagrams(final Integer diagrams );
    public void addRefdiagrams(final Integer refdiagrams );

    @OslcName("name")
    @OslcPropertyDefinition(Oslc_objectiverDomainConstants.OBJECTIVERWEB_NAMSPACE + "name")
    @OslcOccurs(Occurs.ExactlyOne)
    @OslcValueType(ValueType.String)
    @OslcReadOnly(false)
    public String getName();

    @OslcName("type")
    @OslcPropertyDefinition(Oslc_objectiverDomainConstants.OBJECTIVERWEB_NAMSPACE + "type")
    @OslcOccurs(Occurs.ExactlyOne)
    @OslcValueType(ValueType.String)
    @OslcReadOnly(false)
    public String getType();

    @OslcName("def")
    @OslcPropertyDefinition(Oslc_objectiverDomainConstants.OBJECTIVERWEB_NAMSPACE + "def")
    @OslcOccurs(Occurs.ExactlyOne)
    @OslcValueType(ValueType.String)
    @OslcReadOnly(false)
    public String getDef();

    @OslcName("priority")
    @OslcPropertyDefinition(Oslc_objectiverDomainConstants.OBJECTIVERWEB_NAMSPACE + "priority")
    @OslcOccurs(Occurs.ExactlyOne)
    @OslcValueType(ValueType.String)
    @OslcReadOnly(false)
    public String getPriority();

    @OslcName("category")
    @OslcPropertyDefinition(Oslc_objectiverDomainConstants.OBJECTIVERWEB_NAMSPACE + "category")
    @OslcOccurs(Occurs.ExactlyOne)
    @OslcValueType(ValueType.String)
    @OslcReadOnly(false)
    public String getCategory();

    @OslcName("issue")
    @OslcPropertyDefinition(Oslc_objectiverDomainConstants.OBJECTIVERWEB_NAMSPACE + "issue")
    @OslcOccurs(Occurs.ExactlyOne)
    @OslcValueType(ValueType.String)
    @OslcReadOnly(false)
    public String getIssue();

    @OslcName("externalId")
    @OslcPropertyDefinition(Oslc_objectiverDomainConstants.OBJECTIVERWEB_NAMSPACE + "externalId")
    @OslcOccurs(Occurs.ExactlyOne)
    @OslcValueType(ValueType.String)
    @OslcReadOnly(false)
    public String getExternalId();

    @OslcName("openId")
    @OslcPropertyDefinition(Oslc_objectiverDomainConstants.OBJECTIVERWEB_NAMSPACE + "openId")
    @OslcOccurs(Occurs.ExactlyOne)
    @OslcValueType(ValueType.String)
    @OslcReadOnly(false)
    public String getOpenId();

    @OslcName("diagrams")
    @OslcPropertyDefinition(Oslc_objectiverDomainConstants.OBJECTIVERWEB_NAMSPACE + "diagrams")
    @OslcOccurs(Occurs.ZeroOrMany)
    @OslcValueType(ValueType.Integer)
    @OslcReadOnly(false)
    public Set<Integer> getDiagrams();

    @OslcName("refdiagrams")
    @OslcPropertyDefinition(Oslc_objectiverDomainConstants.OBJECTIVERWEB_NAMSPACE + "refdiagrams")
    @OslcOccurs(Occurs.ZeroOrMany)
    @OslcValueType(ValueType.Integer)
    @OslcReadOnly(false)
    public Set<Integer> getRefdiagrams();


    public void setName(final String name );
    public void setType(final String type );
    public void setDef(final String def );
    public void setPriority(final String priority );
    public void setCategory(final String category );
    public void setIssue(final String issue );
    public void setExternalId(final String externalId );
    public void setOpenId(final String openId );
    public void setDiagrams(final Set<Integer> diagrams );
    public void setRefdiagrams(final Set<Integer> refdiagrams );
}

