// Start of user code Copyright
/*
 * Copyright (c) 2020 Contributors to the Eclipse Foundation
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Distribution License 1.0 which is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Simple
 *
 * This file is generated by Lyo Designer (https://www.eclipse.org/lyo/)
 */
// End of user code

package cetic.be.objectiver.oslc.resources;

import org.eclipse.lyo.oslc4j.core.model.OslcConstants;


// Start of user code imports
// End of user code

public interface Oslc_objectiverDomainConstants
{
    // Start of user code user constants
    // End of user code

    public static String OBJECTIVERWEB_DOMAIN = "http://cetic.be.objectiver.oslc/nsp4#";
    public static String OBJECTIVERWEB_NAMSPACE = "http://cetic.be.objectiver.oslc/nsp4#";
    public static String OBJECTIVERWEB_NAMSPACE_PREFIX = "oslc_objectiver";

    public static String GOAL_PATH = "goal";
    public static String GOAL_NAMESPACE = OBJECTIVERWEB_NAMSPACE; //namespace of the rdfs:class the resource describes
    public static String GOAL_LOCALNAME = "Goal"; //localName of the rdfs:class the resource describes
    public static String GOAL_TYPE = GOAL_NAMESPACE + GOAL_LOCALNAME; //fullname of the rdfs:class the resource describes
}
